# ====================== Agent 模型名称配置 ======================
chat_model_name: qwen3-max
embedding_model_name: text-embedding-v4
huggingface_embedding_model_name: all-MiniLM-L6-v2

# ====================== Doubao Seed 配置 ======================
doubao-seed-2-0-mini_model_name: doubao-seed-2-0-mini-260428
doubao_seed_api_endpoint: "https://ark.cn-beijing.volces.com/api/v3"
doubao_seed_full_endpoint: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
doubao_seed_timeout: 30
doubao_seed_thinking_mode: "disabled"

# ====================== InternVL 配置 ======================
internvl2-8b_model_name: OpenGVLab/InternVL2-8B
internvl3-5-8b_model_name: OpenGVLab/InternVL3_5-8B
internvl_api_endpoint: "http://i-2.gpushare.com:24667/v1"
internvl_full_endpoint: "http://i-2.gpushare.com:24667/v1/chat/completions"
internvl_api_key: "vllm-dummy-api-key"
internvl_temperature: 0.2
internvl_timeout: 30
internvl_max_tokens: 8192
